### ISSUE TITLE
TODO elo-pool.com

### ISSUE THREAD

**Issue by Tenosiey** [Tenosiey/elo-pool#1]
# TODO elo-pool.com:
- [ ] Frontend to backend communication authorized
    - [ ] OAuth2?
    - [ ] API-Key?
- [ ] Create a basic frontend
    - [ ] Players can enter usernames, games they play
        - [ ] Create the corresponding database entry's
        - [ ] with buttons for starting games
    - [ ] Players can challenge other players
        - [ ] Friendlist?
        - [ ] Gamecode?
        - [ ] QR-code?
    - [ ] Players can win / lose a Game
        - [ ] Update a players stats
    - [ ] Player can look at his own stats
